### ISSUE TITLE
Set priority is not working after hard fork...

### ISSUE THREAD

**Issue by jq8778** [scala-network/scala-v7#13]
Hello dev team,

Before the hard fork updated the "Set priority" command of cli wallet used to work well, but after hard fork i find that the tx fee just do not change even i set priority as 4. Can u please find out why this happen?

Thanks

**Comment by 0x3h** [comment]
Obviously, the so called "team" doesn't exists or doesn't really care.. After the fork TXs are taking hours to get the first confirmations plus you must split big transfers because it cannot fit for some reason. This is really getting really frustrating; I'll go back to monero it's more profitable not to mention other benefits. I really hope Stellite doesn't turn out to be a shitcoin after all but with this unsolved problems and it's careless team I'm really afraid it will be soon.

**Comment by scala-network** [comment]
Yes there was a small bug in code, we're fixing this in today's release along with sync issues that some people seem to be having.
